name: Deploy Client Frontend to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Permissions
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" | sed 's/\\n/\n/g' > key.pem
          chmod 600 key.pem

      - name: Sync Client Frontend to Droplet
        env:
          SSH_HOST: huytran3.workspace.opstech.org
          SSH_USER: alsp
        run: |
          rsync -avz --exclude='node_modules' --exclude='.git' --exclude='.github' \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ $SSH_USER@$SSH_HOST:/var/www/client-frontend

      - name: Run Deploy Script for Client Frontend
        env:
          SSH_HOST: huytran3.workspace.opstech.org
          SSH_USER: alsp
        run: |
          ssh -i key.pem $SSH_USER@$SSH_HOST "
            cd /var/www/client-frontend &&
            chmod +x deploy.sh &&
            ./deploy.sh
          "
